version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "17:00"
      timezone: "Europe/Helsinki"
    open-pull-requests-limit: 10
    reviewers:
      - jerr0328
    commit-message:
      prefix: "⬆️"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "17:00"
      timezone: "Europe/Helsinki"
    reviewers:
      - jerr0328
    commit-message:
      prefix: "⬆️"
